### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'name')   To help us fix this error, please:

### ISSUE THREAD

**Issue by WillD77** [FIRSTTeam102/ScoringApp-Serverless#137]
https://www.scoutradioz.com/frc386/manage/

TypeError: Cannot read properties of undefined (reading 'name')
    at eval (eval at wrap (/var/task/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:177:63)
    at eval (eval at wrap (/var/task/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:192:4)
    at template (eval at wrap (/var/task/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:299:7)
    at exports.renderFile (/var/task/node_modules/pug/lib/index.js:454:38)
    at exports.renderFile (/var/task/node_modules/pug/lib/index.js:444:21)
    at exports.__express [as engine] (/var/task/node_modules/pug/lib/index.js:493:11)
    at View.render (/var/task/node_modules/express/lib/view.js:135:8)
    at tryRender (/var/task/node_modules/express/lib/application.js:657:10)
    at Function.render (/var/task/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/var/task/node_modules/express/lib/response.js:1039:7)

Did we miss a step in setting up team stuff?

Thanks,
Will

**Comment by JL102** [comment]
Can no longer reproduce on the current version of the site.
